### ISSUE TITLE
Function check is not good when using native async funcitons

### ISSUE THREAD

**Issue by tommytroylin** [recore/refast#11]
test code:
```javascript
function isType(type) {
  return obj => ({}.toString.call(obj) === `[object ${type}]`);
}
var isFunction = isType('Function');
const ayncFunc = async function() {};
console.log('is native async function function? ', isFunction(ayncFunc));
```

https://github.com/recore/refast/blob/8d1677364e9b8037293d7634695368617443ed12/src/lib/Component.jsx#L52

native async functions will fail on this function check and throw an error that action xxxx should be a function.

```javascript
({}).toString.call(async function() {}); // [object AsyncFunction]
```

simply use `typeof ` should be good

**Comment by fengsx** [comment]
refast@^2.1.1 has fixed .
