### ISSUE TITLE
refast里的logic.js是怎么来的呢？

### ISSUE THREAD

**Issue by xiaoliushifu** [recore/refast#12]
扫了好几遍文档，五分钟上手的东西，我看了一天多了也没成功过一个demo，咋回事呢？

**Comment by fengsx** [comment]
你可以看下 [demo](https://github.com/recore/refast-demo)。Refast 只是一个库，项目文件你可以通过脚手架去实现。

**Comment by xiaoliushifu** [comment]
后来有人告诉我，logic.js是自己创建的而已，嘿嘿，就差这句话了。
