### ISSUE TITLE
LogicRender 支持条件渲染

### ISSUE THREAD

**Issue by micate** [recore/refast#6]
可以根据传入的 `prop` 是否为 `true`，决定是否渲染 `<LogicRender></LogicRender>` 内部的子元素。

如果不渲染的话，最好是 `null` 而不是一个空白的子元素，如 `<div />`。

**Comment by fengsx** [comment]
这部分已开发，但是未放入文档中。目前文档已更新。`props`名为`show`，可以直接使用。
