### ISSUE TITLE
logic 只负责对应的组件的状态更新?

### ISSUE THREAD

**Issue by AceLeeWinnie** [recore/refast#7]
如题。如果遇到子组件状态影响父组件状态，是否仍旧是通过层层传递 action 的方式完成？如果两个组件是并列关系，是否需要把 action 都挂载到上层组件，然后通过传递的方式才能完成？有没有类似 redux 统一管理的地方，还是可以和 redux 一起使用？求解答，多谢~

**Comment by fengsx** [comment]
是的，logic 只负责其绑定的对应组件的状态更新。你文中讲的方法是可以的。如果设计良好，与 redux 也是可以一起使用的（强烈不推荐）。
